#!/bin/bash

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee no-scaling-yes-preset-newton-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee auto-scaling-yes-preset-newton-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee under-scaling-yes-preset-newton-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee no-scaling-no-preset-newton-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee auto-scaling-no-preset-newton-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 0 2>&1 | tee under-scaling-no-preset-newton-amg.log

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee no-scaling-yes-preset-pjfnk-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee auto-scaling-yes-preset-pjfnk-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee under-scaling-yes-preset-pjfnk-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee no-scaling-no-preset-pjfnk-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee auto-scaling-no-preset-pjfnk-amg.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type hypre -pc_hypre_type boomeramg -snes_mf_operator 1 2>&1 | tee under-scaling-no-preset-pjfnk-amg.log

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee no-scaling-yes-preset-newton-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee auto-scaling-yes-preset-newton-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee under-scaling-yes-preset-newton-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee no-scaling-no-preset-newton-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee auto-scaling-no-preset-newton-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 0 2>&1 | tee under-scaling-no-preset-newton-ilu.log

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee no-scaling-yes-preset-pjfnk-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee auto-scaling-yes-preset-pjfnk-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee under-scaling-yes-preset-pjfnk-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee no-scaling-no-preset-pjfnk-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee auto-scaling-no-preset-pjfnk-ilu.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type ilu -snes_mf_operator 1 2>&1 | tee under-scaling-no-preset-pjfnk-ilu.log

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee no-scaling-yes-preset-newton-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee auto-scaling-yes-preset-newton-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee under-scaling-yes-preset-newton-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee no-scaling-no-preset-newton-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee auto-scaling-no-preset-newton-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 0 2>&1 | tee under-scaling-no-preset-newton-none.log

./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee no-scaling-yes-preset-pjfnk-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=true -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee auto-scaling-yes-preset-pjfnk-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=true GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee under-scaling-yes-preset-pjfnk-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee no-scaling-no-preset-pjfnk-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=true GlobalParams/preset=false -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee auto-scaling-no-preset-pjfnk-none.log
./contact-oprof -i al-input.i Executioner/automatic_scaling=false GlobalParams/preset=false GlobalParams/scaling=1e-12 -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-8 -pc_type none -snes_mf_operator 1 2>&1 | tee under-scaling-no-preset-pjfnk-none.log
