#!/bin/bash

mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=false Outputs/print_linear_residuals=false GlobalParams/preset=true -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 0 2>&1 | tee no-scaling-yes-preset-newton-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=true Outputs/print_linear_residuals=false GlobalParams/preset=true -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 0 2>&1 | tee auto-scaling-yes-preset-newton-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=false Outputs/print_linear_residuals=false GlobalParams/preset=false -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 0 2>&1 | tee no-scaling-no-preset-newton-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=true Outputs/print_linear_residuals=false GlobalParams/preset=false -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 0 2>&1 | tee auto-scaling-no-preset-newton-asm-full-solve.log

mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=false Outputs/print_linear_residuals=false GlobalParams/preset=true -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 1 2>&1 | tee no-scaling-yes-preset-pjfnk-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=true Outputs/print_linear_residuals=false GlobalParams/preset=true -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 1 2>&1 | tee auto-scaling-yes-preset-pjfnk-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=false Outputs/print_linear_residuals=false GlobalParams/preset=false -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 1 2>&1 | tee no-scaling-no-preset-pjfnk-asm-full-solve.log
mpiexec -np 2 ../darcy_thermo_mech-oprof -i step4.i Executioner/automatic_scaling=true Outputs/print_linear_residuals=false GlobalParams/preset=false -ksp_monitor_true_residual -ksp_gmres_restart 1000 -ksp_max_it 1000 -snes_rtol 1e-12 -ksp_rtol 1e-12 -options_left -pc_type asm -snes_mf_operator 1 2>&1 | tee auto-scaling-no-preset-pjfnk-asm-full-solve.log
